export enum ActivityTypeEnum {
  VIDEO = "VIDEO",
  DIALOG = "DIALOG",
  MULTIPLE_RESPONSE = "MULTIPLE_RESPONSE",
  IMAGE = "IMAGE",
  COMPLETE_SENTENCE = "COMPLETE_SENTENCE",
  TRUE_OR_FALSE = "TRUE_OR_FALSE"
}
