export enum SentencePersonIconEnum {
  SOLINHO = "SOLINHO",
  ANA_SECRETARIA = "ANA_SECRETARIA",
  CLARA_SECRETARIA = "CLARA_SECRETARIA",
  PAULO_ENFERMEIRO = "PAULO_ENFERMEIRO",
  GIOVANA_ENFERMEIRA = "GIOVANA_ENFERMEIRA",
  JOAO = "JOAO",
  JOAQUIM = "JOAQUIM",
  MARIA = "MARIA"
}
